spring:
  datasource:
    driverClassName: org.postgresql.Driver
#    deploy
    url: jdbc:postgresql://dpg-cidaetunqqlb62hvb54g-a/getandpost
#    local
#    url: jdbc:postgresql://dpg-cidaetunqqlb62hvb54g-a.oregon-postgres.render.com/getandpost
    username: postgress
    password: We803xCsTAN7k6g1wyv13VP2mOq6fbiO
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080